name = "MathJSONComputeEngineBridge"
uuid = "c09e7786-a2fb-4839-8ffe-e6218df50e91"
version = "0.3.0"
authors = ["Sébastien Celles <s.celles@gmail.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathJSON = "77215b4b-6f01-425c-beac-950ae6536d4d"

[weakdeps]
Giac = "e4421f97-9838-4fd0-9fa5-94f11373bf78"

[extensions]
GiacBackendExt = "Giac"

[compat]
Aqua = "0.8"
Giac = "0.9"
LinearAlgebra = "1"
MathJSON = "0.2"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Giac = "e4421f97-9838-4fd0-9fa5-94f11373bf78"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Giac", "Test"]
