name = "MathJSONComputeEngineBridge"
uuid = "c09e7786-a2fb-4839-8ffe-e6218df50e91"
version = "0.1.0"
authors = ["Sébastien Celles <s.celles@gmail.com>"]

[deps]
MathJSON = "77215b4b-6f01-425c-beac-950ae6536d4d"

[compat]
Aqua = "0.8"
MathJSON = "0.2"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
